name: uwdatasci400

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.6
  - pandas=1.0.1
  - scikit-learn=0.22.2
  - seaborn=0.10.0
  - joblib=0.14.1
  - jupyter=1.0.0
  - mlxtend=0.17.2
  - graphviz=2.38
  - pip=20.0.2
  - requests=2.23.0
  - pyyaml=5.3.1
  - pillow=7.1.1

  - pip:
    - pylint==2.4.4
    - bs4==0.0.1
